version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: test123
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
