name: Deploy Flask App to VM using Docker Compose

on:
  push:
    branches:
      - dockerize-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up sshpass
      run: sudo apt-get install -y sshpass

    - name: Transfer application files to VM
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no \
        -r . ${{ secrets.VM_USER }}@${{ secrets.VM_PUBLIC_IP }}:/tmp/flask-app

    - name: SSH into VM and deploy with Docker Compose
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_PUBLIC_IP }} << 'EOF'
          # Move to the app directory
          cd /tmp/flask-app

          # Pull the latest Docker images (if needed) and restart the containers
          docker-compose down
          docker-compose up -d --build
        EOF
