name: Deploy Flask App to VM using Docker Compose

on:
  push:
    branches:
      - dockerize-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up sshpass
      run: sudo apt-get install -y sshpass

    - name: Compress application files
      run: zip -r flask-app.zip .

    - name: Transfer zipped application to VM
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no \
        flask-app.zip ${{ secrets.VM_USER }}@${{ secrets.VM_PUBLIC_IP }}:/tmp/

    - name: SSH into VM and deploy with Docker Compose
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_PUBLIC_IP }} << 'EOF'
          # Move to the /tmp directory
          cd /tmp

          # Unzip the transferred application
          unzip -o flask-app.zip -d flask-app
          cd flask-app

          # Deploy with Docker Compose
          docker-compose down
          docker-compose up -d --build
        EOF
